# Generated by Django 4.1.4 on 2023-01-06 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_useraccount_friends_friendrequest_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_request_from_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
